// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(flower_ffiFFI)
import flower_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_flower_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_flower_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * A live flower document bound for a native Apple frontend: a
 * `flower_core::Model` over a [`FigBackend`], behind a mutex. Constructed from
 * in-memory bytes and driven entirely through method calls — there is no
 * filesystem behind it; the host reads the file and persists [`FlowerDoc::source`].
 */
public protocol FlowerDocProtocol : AnyObject {
    
    /**
     * Append `text` to the **sequence** at `index`, typing the value by the
     * schema's rule for the sequence's *items* and otherwise by literal shape. A
     * no-op with a status hint when the row isn't a sequence.
     */
    func appendItem(index: UInt32, text: String)  -> DocView
    
    /**
     * Append `text` at the **document root** (a top-level sequence item). The
     * root-level counterpart to [`append_item`](Self::append_item). A no-op with
     * a status hint when the root isn't a sequence.
     */
    func appendRootItem(text: String)  -> DocView
    
    /**
     * `←` semantics: collapse an expanded container, else step out to the parent.
     */
    func collapseOrLeave()  -> DocView
    
    /**
     * Delete the mapping entry or sequence item at `index`, refreshing the view.
     */
    func delete(index: UInt32)  -> DocView
    
    /**
     * `→` semantics: expand a collapsed container, else step into its first child.
     */
    func expandOrEnter()  -> DocView
    
    /**
     * Insert `key = text` into the **mapping** at `index`, typing the value by the
     * schema's rule for the new entry and otherwise by literal shape. A no-op with
     * a status hint when the row isn't a mapping; the backend rejects a duplicate
     * key.
     */
    func insertKey(index: UInt32, key: String, text: String)  -> DocView
    
    /**
     * Insert `key = text` at the **document root** (a top-level mapping entry),
     * typed the same way [`insert_key`](Self::insert_key) types one. The
     * root-level counterpart — there is no root row to target by index. A no-op
     * with a status hint when the root isn't a mapping.
     */
    func insertRootKey(key: String, text: String)  -> DocView
    
    /**
     * Mark the document saved after the host persisted [`FlowerDoc::source`] its
     * own way — clears the dirty flag without touching a filesystem.
     */
    func markSaved()  -> DocView
    
    func moveDown()  -> DocView
    
    /**
     * Move the row at `index` one place later among its siblings.
     */
    func moveRowDown(index: UInt32)  -> DocView
    
    /**
     * Move the row at `index` one place earlier among its siblings.
     */
    func moveRowUp(index: UInt32)  -> DocView
    
    func moveUp()  -> DocView
    
    /**
     * Add a child to the container `id` names: `key = text` for a mapping, an
     * appended `text` for a sequence. `""` is the document root.
     *
     * One method for both because a page names its own container by id — adding
     * "to this page" and adding "to that row" are the same call with a different
     * id, which is not true of the tree, where the root has no row.
     */
    func pageAddChild(id: String, key: String, text: String)  -> PagesView
    
    /**
     * The page listing what `id` names, **without navigating to it** — `""` for
     * the document root.
     *
     * The read-only counterpart to [`page_open`](Self::page_open), for a frontend
     * whose navigation is a stack: the OS asks it to render the screen for a path
     * element that is not the one in front, and answering that by moving the
     * focus would make drawing a screen a navigation. It carries the cursor only
     * when `id` *is* the page you are on; an ancestor is a page you are not
     * standing on, and drawing a selection there would claim otherwise.
     *
     * Total: an id that names nothing, or names a scalar, yields an empty page,
     * so a destination builder always has something to render.
     */
    func pageAt(id: String)  -> PageView
    
    /**
     * Pop back to the parent page, restoring the cursor to the container you came
     * out of.
     */
    func pageBack()  -> PagesView
    
    /**
     * Delete the mapping entry or sequence item `id` names.
     */
    func pageDelete(id: String)  -> PagesView
    
    /**
     * Move the cursor one item down the current page (`↓`).
     */
    func pageMoveDown()  -> PagesView
    
    /**
     * Move the item `id` names one place later among its siblings.
     */
    func pageMoveItemDown(id: String)  -> PagesView
    
    /**
     * Move the item `id` names one place earlier among its siblings.
     */
    func pageMoveItemUp(id: String)  -> PagesView
    
    /**
     * Move the cursor one item up the current page (`↑`).
     */
    func pageMoveUp()  -> PagesView
    
    /**
     * Open what `id` names as a page — a tap on a drill row, on a row in the
     * pane you came out of, or on a breadcrumb. `""` opens the document root.
     *
     * A scalar or a group header has no page of its own, so this only selects it
     * (a group's members are already listed under it; a scalar is edited in
     * place through [`page_set_value`](Self::page_set_value)).
     */
    func pageOpen(id: String)  -> PagesView
    
    /**
     * Rename the mapping entry `id` names, keeping its value. A no-op with a
     * status hint on a sequence item, which has an index, not a key.
     */
    func pageRename(id: String, newKey: String)  -> PagesView
    
    /**
     * Put the cursor on the item `id` names, pointing the page view at whichever
     * page *lists* it. A tap on a row.
     *
     * `""` is the document root, which selects nothing and lists the root page.
     */
    func pageSelect(id: String)  -> PagesView
    
    /**
     * Commit `text` as the new value of the scalar `id` names, spliced losslessly
     * through fig — the page-view peer of [`set_value`](Self::set_value).
     */
    func pageSetValue(id: String, text: String)  -> PagesView
    
    /**
     * The page frame as it stands, without switching projection — for a host that
     * keeps both surfaces rendered and needs to refresh the one an edit was not
     * made from.
     */
    func pages()  -> PagesView
    
    /**
     * Rename the mapping entry at `index` to `new_key`, keeping its value. A
     * no-op with a status hint when the row is a sequence item (no key); the
     * backend rejects a name that collides with a sibling.
     */
    func renameKey(index: UInt32, newKey: String)  -> DocView
    
    /**
     * Select the row at `index` (clamped). The coordinate a `List` selection or a
     * tap speaks; the other index-taking methods select first, so a caller can
     * drive purely by index.
     */
    func select(index: UInt32)  -> DocView
    
    /**
     * Set how much of a container's subtree the page projection inlines rather
     * than drills: at most `rows` rows per inlined subtree (every descendant is
     * one — nested headers included), reaching at most `depth` ranks of inset.
     *
     * The default (6 rows, 1 rank) is the settings-menu rule: small all-scalar
     * groups inline, everything substantial earns a page. Raised past the
     * document's size, the root page simply *is* the whole document — the
     * settings-list rendering, without a second surface. The host picks,
     * because the right amount is a fact about the room the pages are drawn
     * in, not about the document.
     */
    func setInlineBudget(rows: UInt32, depth: UInt32)  -> PagesView
    
    /**
     * Commit `text` as the new value of the scalar row at `index`, splicing it
     * losslessly through fig's editor. The type is the one the schema declares for
     * that path, or — with no schema, the standalone-config case — a guess from
     * the literal's shape (`true`/`42`/`3.14`/`null`/text). A no-op on a container
     * row. The status reflects success or the backend's rejection.
     */
    func setValue(index: UInt32, text: String)  -> DocView
    
    /**
     * Switch to the page view and resolve it to a renderable frame.
     *
     * The switch carries the cursor across: the node selected in the tree is the
     * node selected on the page you land on, so the two views are two ways of
     * looking at one position rather than two places.
     */
    func showPages()  -> PagesView
    
    /**
     * Switch back to the tree view, carrying the cursor the same way.
     */
    func showTree()  -> DocView
    
    /**
     * The canonical serialized document — what the host writes on save.
     */
    func source()  -> String
    
    /**
     * Toggle the container at `index` between expanded and collapsed (a
     * disclosure-triangle tap). Selects the row; a no-op on a scalar row (the
     * frontend edits those in place instead).
     */
    func toggle(index: UInt32)  -> DocView
    
    /**
     * Resolve the current document to a renderable frame — the first paint.
     */
    func view()  -> DocView
    
}

/**
 * A live flower document bound for a native Apple frontend: a
 * `flower_core::Model` over a [`FigBackend`], behind a mutex. Constructed from
 * in-memory bytes and driven entirely through method calls — there is no
 * filesystem behind it; the host reads the file and persists [`FlowerDoc::source`].
 */
open class FlowerDoc:
    FlowerDocProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_flower_ffi_fn_clone_flowerdoc(self.pointer, $0) }
    }
    /**
     * Parse `source` as `format` (`"json"`/`"jsonc"`/`"json5"`, `"yaml"`/`"yml"`,
     * `"toml"`, `"zon"`, `"fig"`/`"figl"`) into a live, untitled document.
     *
     * `hidden_keys` are **top-level** mapping keys to hide from the row
     * projection while keeping them in the document (byte-for-byte). Pass `[]`
     * for a standalone config; a prov/diaryx frontend passes the managed-key set
     * so those fields stay lossless and out of view. The list is the caller's to
     * supply — flower stays format-agnostic and never names those keys itself.
     */
public convenience init(source: String, format: String, hiddenKeys: [String])throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeFlowerError.lift) {
    uniffi_flower_ffi_fn_constructor_flowerdoc_new(
        FfiConverterString.lower(source),
        FfiConverterString.lower(format),
        FfiConverterSequenceString.lower(hiddenKeys),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_flower_ffi_fn_free_flowerdoc(pointer, $0) }
    }

    

    
    /**
     * Append `text` to the **sequence** at `index`, typing the value by the
     * schema's rule for the sequence's *items* and otherwise by literal shape. A
     * no-op with a status hint when the row isn't a sequence.
     */
open func appendItem(index: UInt32, text: String) -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_append_item(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(index),
        FfiConverterString.lower(text),$0
    )
})
}
    
    /**
     * Append `text` at the **document root** (a top-level sequence item). The
     * root-level counterpart to [`append_item`](Self::append_item). A no-op with
     * a status hint when the root isn't a sequence.
     */
open func appendRootItem(text: String) -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_append_root_item(self.uniffiClonePointer(),
        FfiConverterString.lower(text),$0
    )
})
}
    
    /**
     * `←` semantics: collapse an expanded container, else step out to the parent.
     */
open func collapseOrLeave() -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_collapse_or_leave(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Delete the mapping entry or sequence item at `index`, refreshing the view.
     */
open func delete(index: UInt32) -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_delete(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(index),$0
    )
})
}
    
    /**
     * `→` semantics: expand a collapsed container, else step into its first child.
     */
open func expandOrEnter() -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_expand_or_enter(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Insert `key = text` into the **mapping** at `index`, typing the value by the
     * schema's rule for the new entry and otherwise by literal shape. A no-op with
     * a status hint when the row isn't a mapping; the backend rejects a duplicate
     * key.
     */
open func insertKey(index: UInt32, key: String, text: String) -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_insert_key(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(index),
        FfiConverterString.lower(key),
        FfiConverterString.lower(text),$0
    )
})
}
    
    /**
     * Insert `key = text` at the **document root** (a top-level mapping entry),
     * typed the same way [`insert_key`](Self::insert_key) types one. The
     * root-level counterpart — there is no root row to target by index. A no-op
     * with a status hint when the root isn't a mapping.
     */
open func insertRootKey(key: String, text: String) -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_insert_root_key(self.uniffiClonePointer(),
        FfiConverterString.lower(key),
        FfiConverterString.lower(text),$0
    )
})
}
    
    /**
     * Mark the document saved after the host persisted [`FlowerDoc::source`] its
     * own way — clears the dirty flag without touching a filesystem.
     */
open func markSaved() -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_mark_saved(self.uniffiClonePointer(),$0
    )
})
}
    
open func moveDown() -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_move_down(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Move the row at `index` one place later among its siblings.
     */
open func moveRowDown(index: UInt32) -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_move_row_down(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(index),$0
    )
})
}
    
    /**
     * Move the row at `index` one place earlier among its siblings.
     */
open func moveRowUp(index: UInt32) -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_move_row_up(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(index),$0
    )
})
}
    
open func moveUp() -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_move_up(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Add a child to the container `id` names: `key = text` for a mapping, an
     * appended `text` for a sequence. `""` is the document root.
     *
     * One method for both because a page names its own container by id — adding
     * "to this page" and adding "to that row" are the same call with a different
     * id, which is not true of the tree, where the root has no row.
     */
open func pageAddChild(id: String, key: String, text: String) -> PagesView {
    return try!  FfiConverterTypePagesView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_page_add_child(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(key),
        FfiConverterString.lower(text),$0
    )
})
}
    
    /**
     * The page listing what `id` names, **without navigating to it** — `""` for
     * the document root.
     *
     * The read-only counterpart to [`page_open`](Self::page_open), for a frontend
     * whose navigation is a stack: the OS asks it to render the screen for a path
     * element that is not the one in front, and answering that by moving the
     * focus would make drawing a screen a navigation. It carries the cursor only
     * when `id` *is* the page you are on; an ancestor is a page you are not
     * standing on, and drawing a selection there would claim otherwise.
     *
     * Total: an id that names nothing, or names a scalar, yields an empty page,
     * so a destination builder always has something to render.
     */
open func pageAt(id: String) -> PageView {
    return try!  FfiConverterTypePageView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_page_at(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Pop back to the parent page, restoring the cursor to the container you came
     * out of.
     */
open func pageBack() -> PagesView {
    return try!  FfiConverterTypePagesView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_page_back(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Delete the mapping entry or sequence item `id` names.
     */
open func pageDelete(id: String) -> PagesView {
    return try!  FfiConverterTypePagesView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_page_delete(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Move the cursor one item down the current page (`↓`).
     */
open func pageMoveDown() -> PagesView {
    return try!  FfiConverterTypePagesView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_page_move_down(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Move the item `id` names one place later among its siblings.
     */
open func pageMoveItemDown(id: String) -> PagesView {
    return try!  FfiConverterTypePagesView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_page_move_item_down(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Move the item `id` names one place earlier among its siblings.
     */
open func pageMoveItemUp(id: String) -> PagesView {
    return try!  FfiConverterTypePagesView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_page_move_item_up(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Move the cursor one item up the current page (`↑`).
     */
open func pageMoveUp() -> PagesView {
    return try!  FfiConverterTypePagesView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_page_move_up(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Open what `id` names as a page — a tap on a drill row, on a row in the
     * pane you came out of, or on a breadcrumb. `""` opens the document root.
     *
     * A scalar or a group header has no page of its own, so this only selects it
     * (a group's members are already listed under it; a scalar is edited in
     * place through [`page_set_value`](Self::page_set_value)).
     */
open func pageOpen(id: String) -> PagesView {
    return try!  FfiConverterTypePagesView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_page_open(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Rename the mapping entry `id` names, keeping its value. A no-op with a
     * status hint on a sequence item, which has an index, not a key.
     */
open func pageRename(id: String, newKey: String) -> PagesView {
    return try!  FfiConverterTypePagesView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_page_rename(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(newKey),$0
    )
})
}
    
    /**
     * Put the cursor on the item `id` names, pointing the page view at whichever
     * page *lists* it. A tap on a row.
     *
     * `""` is the document root, which selects nothing and lists the root page.
     */
open func pageSelect(id: String) -> PagesView {
    return try!  FfiConverterTypePagesView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_page_select(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Commit `text` as the new value of the scalar `id` names, spliced losslessly
     * through fig — the page-view peer of [`set_value`](Self::set_value).
     */
open func pageSetValue(id: String, text: String) -> PagesView {
    return try!  FfiConverterTypePagesView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_page_set_value(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(text),$0
    )
})
}
    
    /**
     * The page frame as it stands, without switching projection — for a host that
     * keeps both surfaces rendered and needs to refresh the one an edit was not
     * made from.
     */
open func pages() -> PagesView {
    return try!  FfiConverterTypePagesView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_pages(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Rename the mapping entry at `index` to `new_key`, keeping its value. A
     * no-op with a status hint when the row is a sequence item (no key); the
     * backend rejects a name that collides with a sibling.
     */
open func renameKey(index: UInt32, newKey: String) -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_rename_key(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(index),
        FfiConverterString.lower(newKey),$0
    )
})
}
    
    /**
     * Select the row at `index` (clamped). The coordinate a `List` selection or a
     * tap speaks; the other index-taking methods select first, so a caller can
     * drive purely by index.
     */
open func select(index: UInt32) -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_select(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(index),$0
    )
})
}
    
    /**
     * Set how much of a container's subtree the page projection inlines rather
     * than drills: at most `rows` rows per inlined subtree (every descendant is
     * one — nested headers included), reaching at most `depth` ranks of inset.
     *
     * The default (6 rows, 1 rank) is the settings-menu rule: small all-scalar
     * groups inline, everything substantial earns a page. Raised past the
     * document's size, the root page simply *is* the whole document — the
     * settings-list rendering, without a second surface. The host picks,
     * because the right amount is a fact about the room the pages are drawn
     * in, not about the document.
     */
open func setInlineBudget(rows: UInt32, depth: UInt32) -> PagesView {
    return try!  FfiConverterTypePagesView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_set_inline_budget(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(rows),
        FfiConverterUInt32.lower(depth),$0
    )
})
}
    
    /**
     * Commit `text` as the new value of the scalar row at `index`, splicing it
     * losslessly through fig's editor. The type is the one the schema declares for
     * that path, or — with no schema, the standalone-config case — a guess from
     * the literal's shape (`true`/`42`/`3.14`/`null`/text). A no-op on a container
     * row. The status reflects success or the backend's rejection.
     */
open func setValue(index: UInt32, text: String) -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_set_value(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(index),
        FfiConverterString.lower(text),$0
    )
})
}
    
    /**
     * Switch to the page view and resolve it to a renderable frame.
     *
     * The switch carries the cursor across: the node selected in the tree is the
     * node selected on the page you land on, so the two views are two ways of
     * looking at one position rather than two places.
     */
open func showPages() -> PagesView {
    return try!  FfiConverterTypePagesView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_show_pages(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Switch back to the tree view, carrying the cursor the same way.
     */
open func showTree() -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_show_tree(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * The canonical serialized document — what the host writes on save.
     */
open func source() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_source(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Toggle the container at `index` between expanded and collapsed (a
     * disclosure-triangle tap). Selects the row; a no-op on a scalar row (the
     * frontend edits those in place instead).
     */
open func toggle(index: UInt32) -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_toggle(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(index),$0
    )
})
}
    
    /**
     * Resolve the current document to a renderable frame — the first paint.
     */
open func view() -> DocView {
    return try!  FfiConverterTypeDocView.lift(try! rustCall() {
    uniffi_flower_ffi_fn_method_flowerdoc_view(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFlowerDoc: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FlowerDoc

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FlowerDoc {
        return FlowerDoc(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FlowerDoc) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FlowerDoc {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FlowerDoc, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFlowerDoc_lift(_ pointer: UnsafeMutableRawPointer) throws -> FlowerDoc {
    return try FfiConverterTypeFlowerDoc.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFlowerDoc_lower(_ value: FlowerDoc) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFlowerDoc.lower(value)
}


/**
 * A step of a page's breadcrumb: the container it names, and the id to open it.
 */
public struct CrumbView {
    public var id: String
    public var label: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, label: String) {
        self.id = id
        self.label = label
    }
}



extension CrumbView: Equatable, Hashable {
    public static func ==(lhs: CrumbView, rhs: CrumbView) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.label != rhs.label {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(label)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCrumbView: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CrumbView {
        return
            try CrumbView(
                id: FfiConverterString.read(from: &buf), 
                label: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: CrumbView, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.label, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrumbView_lift(_ buf: RustBuffer) throws -> CrumbView {
    return try FfiConverterTypeCrumbView.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrumbView_lower(_ value: CrumbView) -> RustBuffer {
    return FfiConverterTypeCrumbView.lower(value)
}


/**
 * A whole rendered frame: the visible rows, which is selected, and the
 * document-level chrome state — everything the SwiftUI side needs for one
 * repaint, in one value. Returned by every method.
 */
public struct DocView {
    public var rows: [RowView]
    /**
     * The selected row: an index into [`Self::rows`], clamped to the list.
     */
    public var selected: UInt32
    /**
     * Whether the document differs from the last saved bytes — for a "● modified"
     * affordance and to enable the Save control.
     */
    public var dirty: Bool
    /**
     * The model's one-line status message (last action, or a rejected edit).
     */
    public var status: String
    /**
     * The document root's kind — `"map"`, `"seq"`, or `"scalar"` — so a frontend
     * knows whether a top-level "add" inserts a key or appends an item.
     */
    public var rootKind: String
    /**
     * How many top-level keys are hidden (managed by an embedder). Lets a
     * frontend show a "N managed fields" affordance.
     */
    public var hiddenCount: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(rows: [RowView], 
        /**
         * The selected row: an index into [`Self::rows`], clamped to the list.
         */selected: UInt32, 
        /**
         * Whether the document differs from the last saved bytes — for a "● modified"
         * affordance and to enable the Save control.
         */dirty: Bool, 
        /**
         * The model's one-line status message (last action, or a rejected edit).
         */status: String, 
        /**
         * The document root's kind — `"map"`, `"seq"`, or `"scalar"` — so a frontend
         * knows whether a top-level "add" inserts a key or appends an item.
         */rootKind: String, 
        /**
         * How many top-level keys are hidden (managed by an embedder). Lets a
         * frontend show a "N managed fields" affordance.
         */hiddenCount: UInt32) {
        self.rows = rows
        self.selected = selected
        self.dirty = dirty
        self.status = status
        self.rootKind = rootKind
        self.hiddenCount = hiddenCount
    }
}



extension DocView: Equatable, Hashable {
    public static func ==(lhs: DocView, rhs: DocView) -> Bool {
        if lhs.rows != rhs.rows {
            return false
        }
        if lhs.selected != rhs.selected {
            return false
        }
        if lhs.dirty != rhs.dirty {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        if lhs.rootKind != rhs.rootKind {
            return false
        }
        if lhs.hiddenCount != rhs.hiddenCount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(rows)
        hasher.combine(selected)
        hasher.combine(dirty)
        hasher.combine(status)
        hasher.combine(rootKind)
        hasher.combine(hiddenCount)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDocView: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DocView {
        return
            try DocView(
                rows: FfiConverterSequenceTypeRowView.read(from: &buf), 
                selected: FfiConverterUInt32.read(from: &buf), 
                dirty: FfiConverterBool.read(from: &buf), 
                status: FfiConverterString.read(from: &buf), 
                rootKind: FfiConverterString.read(from: &buf), 
                hiddenCount: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: DocView, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeRowView.write(value.rows, into: &buf)
        FfiConverterUInt32.write(value.selected, into: &buf)
        FfiConverterBool.write(value.dirty, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
        FfiConverterString.write(value.rootKind, into: &buf)
        FfiConverterUInt32.write(value.hiddenCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocView_lift(_ buf: RustBuffer) throws -> DocView {
    return try FfiConverterTypeDocView.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDocView_lower(_ value: DocView) -> RustBuffer {
    return FfiConverterTypeDocView.lower(value)
}


/**
 * One line of a page — the projection of `flower_core::PageItem`.
 *
 * Where a [`RowView`] is a line of the whole document indented by `depth`, this
 * is a line of *one container's* listing: no depth, because everything on a page
 * is one level of the same thing, and an [`inset`](Self::inset) of 1 only for the
 * members of a group inlined into it.
 */
public struct PageItemView {
    /**
     * The item's dotted fig path — the same identity a [`RowView`] carries, so
     * the two projections name a node the same way and every page method takes
     * this string.
     */
    public var id: String
    /**
     * The mapping key, or `[i]` for a sequence item.
     */
    public var label: String
    /**
     * A readable stand-in for a sequence item's index — the value of whichever
     * field best names it. Shown *beside* the label, never instead of it: the
     * index is what the path addresses and what a reorder moves.
     */
    public var title: String?
    /**
     * The value kind as a renderer class id — the same vocabulary
     * [`RowView::kind`] uses.
     */
    public var kind: String
    /**
     * What activating this row does: `"scalar"` (edit in place), `"drill"` (open
     * a page of its own), or `"group"` (the header of a container inlined into
     * this page — its members are the rows below it at `inset` 1).
     */
    public var role: String
    /**
     * A one-line rendering of the value (the scalar text, or `{n}` / `[n]`). For
     * a scalar this is also the seed text an inline editor opens with.
     */
    public var preview: String
    /**
     * A container's whole contents in flow form (`{branches: [master]}`), when
     * they are short enough to be worth showing instead of counting. A renderer
     * prefers this over `count` whenever the row has room for it — `1 field ›`
     * is strictly less than the document says when the field is right there.
     */
    public var summary: String?
    /**
     * How many children a container holds; 0 for a scalar.
     */
    public var count: UInt32
    /**
     * 0 for a direct child of the page's focus; 1 for a member of a group
     * inlined into it, and one more for each further rank the inline budget
     * admitted ([`FlowerDoc::set_inline_budget`]). Under the default budget,
     * never more than 1.
     */
    public var inset: UInt32
    /**
     * Whether this is a mapping entry (its key can be renamed).
     */
    public var canRename: Bool
    /**
     * The names this row shows, outermost first. One element for an ordinary
     * row; several for a **compressed** drill — `["exports", "journal"]`, one
     * row standing for a chain of containers that hold only each other, because
     * the pages in between would each list nothing but the next name down.
     * Join with the same separator the breadcrumb uses. `label` is the first
     * element, and stays what the document calls this entry.
     *
     * Opening it is unchanged: pass `id` to `pageOpen` and it lands at the far
     * end of the chain. Every other op takes `id` too, and acts on the
     * outermost node — so deleting this row deletes the whole chain.
     */
    public var chain: [String]
    /**
     * Whether this item belongs below the fields a reader came to edit — a
     * key the embedder demoted, or anything under one. A host folds these into
     * an "advanced" disclosure; the run of them is already contiguous at the
     * end of a partition, and never cuts an inlined group in half.
     */
    public var demoted: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The item's dotted fig path — the same identity a [`RowView`] carries, so
         * the two projections name a node the same way and every page method takes
         * this string.
         */id: String, 
        /**
         * The mapping key, or `[i]` for a sequence item.
         */label: String, 
        /**
         * A readable stand-in for a sequence item's index — the value of whichever
         * field best names it. Shown *beside* the label, never instead of it: the
         * index is what the path addresses and what a reorder moves.
         */title: String?, 
        /**
         * The value kind as a renderer class id — the same vocabulary
         * [`RowView::kind`] uses.
         */kind: String, 
        /**
         * What activating this row does: `"scalar"` (edit in place), `"drill"` (open
         * a page of its own), or `"group"` (the header of a container inlined into
         * this page — its members are the rows below it at `inset` 1).
         */role: String, 
        /**
         * A one-line rendering of the value (the scalar text, or `{n}` / `[n]`). For
         * a scalar this is also the seed text an inline editor opens with.
         */preview: String, 
        /**
         * A container's whole contents in flow form (`{branches: [master]}`), when
         * they are short enough to be worth showing instead of counting. A renderer
         * prefers this over `count` whenever the row has room for it — `1 field ›`
         * is strictly less than the document says when the field is right there.
         */summary: String?, 
        /**
         * How many children a container holds; 0 for a scalar.
         */count: UInt32, 
        /**
         * 0 for a direct child of the page's focus; 1 for a member of a group
         * inlined into it, and one more for each further rank the inline budget
         * admitted ([`FlowerDoc::set_inline_budget`]). Under the default budget,
         * never more than 1.
         */inset: UInt32, 
        /**
         * Whether this is a mapping entry (its key can be renamed).
         */canRename: Bool, 
        /**
         * The names this row shows, outermost first. One element for an ordinary
         * row; several for a **compressed** drill — `["exports", "journal"]`, one
         * row standing for a chain of containers that hold only each other, because
         * the pages in between would each list nothing but the next name down.
         * Join with the same separator the breadcrumb uses. `label` is the first
         * element, and stays what the document calls this entry.
         *
         * Opening it is unchanged: pass `id` to `pageOpen` and it lands at the far
         * end of the chain. Every other op takes `id` too, and acts on the
         * outermost node — so deleting this row deletes the whole chain.
         */chain: [String], 
        /**
         * Whether this item belongs below the fields a reader came to edit — a
         * key the embedder demoted, or anything under one. A host folds these into
         * an "advanced" disclosure; the run of them is already contiguous at the
         * end of a partition, and never cuts an inlined group in half.
         */demoted: Bool) {
        self.id = id
        self.label = label
        self.title = title
        self.kind = kind
        self.role = role
        self.preview = preview
        self.summary = summary
        self.count = count
        self.inset = inset
        self.canRename = canRename
        self.chain = chain
        self.demoted = demoted
    }
}



extension PageItemView: Equatable, Hashable {
    public static func ==(lhs: PageItemView, rhs: PageItemView) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.label != rhs.label {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.role != rhs.role {
            return false
        }
        if lhs.preview != rhs.preview {
            return false
        }
        if lhs.summary != rhs.summary {
            return false
        }
        if lhs.count != rhs.count {
            return false
        }
        if lhs.inset != rhs.inset {
            return false
        }
        if lhs.canRename != rhs.canRename {
            return false
        }
        if lhs.chain != rhs.chain {
            return false
        }
        if lhs.demoted != rhs.demoted {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(label)
        hasher.combine(title)
        hasher.combine(kind)
        hasher.combine(role)
        hasher.combine(preview)
        hasher.combine(summary)
        hasher.combine(count)
        hasher.combine(inset)
        hasher.combine(canRename)
        hasher.combine(chain)
        hasher.combine(demoted)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePageItemView: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PageItemView {
        return
            try PageItemView(
                id: FfiConverterString.read(from: &buf), 
                label: FfiConverterString.read(from: &buf), 
                title: FfiConverterOptionString.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf), 
                role: FfiConverterString.read(from: &buf), 
                preview: FfiConverterString.read(from: &buf), 
                summary: FfiConverterOptionString.read(from: &buf), 
                count: FfiConverterUInt32.read(from: &buf), 
                inset: FfiConverterUInt32.read(from: &buf), 
                canRename: FfiConverterBool.read(from: &buf), 
                chain: FfiConverterSequenceString.read(from: &buf), 
                demoted: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: PageItemView, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterOptionString.write(value.title, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterString.write(value.role, into: &buf)
        FfiConverterString.write(value.preview, into: &buf)
        FfiConverterOptionString.write(value.summary, into: &buf)
        FfiConverterUInt32.write(value.count, into: &buf)
        FfiConverterUInt32.write(value.inset, into: &buf)
        FfiConverterBool.write(value.canRename, into: &buf)
        FfiConverterSequenceString.write(value.chain, into: &buf)
        FfiConverterBool.write(value.demoted, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePageItemView_lift(_ buf: RustBuffer) throws -> PageItemView {
    return try FfiConverterTypePageItemView.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePageItemView_lower(_ value: PageItemView) -> RustBuffer {
    return FfiConverterTypePageItemView.lower(value)
}


/**
 * One page, ready to render as a pane.
 */
public struct PageView {
    /**
     * The dotted path of the container being listed; `""` is the document root.
     */
    public var focus: String
    /**
     * The trail from the root down to [`focus`](Self::focus), each step openable
     * by its `id`. **Empty at the root**, whose name is the frontend's to choose
     * — flower-core has none for it (the TUI calls it `‹document›`).
     */
    public var crumbs: [CrumbView]
    public var items: [PageItemView]
    /**
     * The selected item, or `None` for a pane that doesn't hold the cursor — a
     * preview, or the parent pane when what it marks is the page you opened.
     */
    public var selected: UInt32?
    /**
     * Whether this whole pane sits under a demoted key — the page you reached
     * by opening a demoted row. Lets a host keep the framing once you are
     * inside, rather than having a section stop applying one level in.
     */
    public var demoted: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The dotted path of the container being listed; `""` is the document root.
         */focus: String, 
        /**
         * The trail from the root down to [`focus`](Self::focus), each step openable
         * by its `id`. **Empty at the root**, whose name is the frontend's to choose
         * — flower-core has none for it (the TUI calls it `‹document›`).
         */crumbs: [CrumbView], items: [PageItemView], 
        /**
         * The selected item, or `None` for a pane that doesn't hold the cursor — a
         * preview, or the parent pane when what it marks is the page you opened.
         */selected: UInt32?, 
        /**
         * Whether this whole pane sits under a demoted key — the page you reached
         * by opening a demoted row. Lets a host keep the framing once you are
         * inside, rather than having a section stop applying one level in.
         */demoted: Bool) {
        self.focus = focus
        self.crumbs = crumbs
        self.items = items
        self.selected = selected
        self.demoted = demoted
    }
}



extension PageView: Equatable, Hashable {
    public static func ==(lhs: PageView, rhs: PageView) -> Bool {
        if lhs.focus != rhs.focus {
            return false
        }
        if lhs.crumbs != rhs.crumbs {
            return false
        }
        if lhs.items != rhs.items {
            return false
        }
        if lhs.selected != rhs.selected {
            return false
        }
        if lhs.demoted != rhs.demoted {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(focus)
        hasher.combine(crumbs)
        hasher.combine(items)
        hasher.combine(selected)
        hasher.combine(demoted)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePageView: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PageView {
        return
            try PageView(
                focus: FfiConverterString.read(from: &buf), 
                crumbs: FfiConverterSequenceTypeCrumbView.read(from: &buf), 
                items: FfiConverterSequenceTypePageItemView.read(from: &buf), 
                selected: FfiConverterOptionUInt32.read(from: &buf), 
                demoted: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: PageView, into buf: inout [UInt8]) {
        FfiConverterString.write(value.focus, into: &buf)
        FfiConverterSequenceTypeCrumbView.write(value.crumbs, into: &buf)
        FfiConverterSequenceTypePageItemView.write(value.items, into: &buf)
        FfiConverterOptionUInt32.write(value.selected, into: &buf)
        FfiConverterBool.write(value.demoted, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePageView_lift(_ buf: RustBuffer) throws -> PageView {
    return try FfiConverterTypePageView.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePageView_lower(_ value: PageView) -> RustBuffer {
    return FfiConverterTypePageView.lower(value)
}


/**
 * A whole rendered frame of the page view: the pane you are on, the pane it came
 * out of, and the one it would open — plus the same document chrome a
 * [`DocView`] carries, so a page-view host needs nothing else.
 */
public struct PagesView {
    /**
     * The page currently being listed, with the cursor on it.
     */
    public var page: PageView
    /**
     * The page one level out — what a two-pane layout draws on the left, with
     * the row you came out of marked. `None` at the root, which has no parent.
     */
    public var parent: PageView?
    /**
     * The page the selection *would* open, so a two-pane layout at the root has
     * something to put on the right before anything has been opened. `None` when
     * the selection is not a drill row.
     */
    public var peek: PageView?
    /**
     * Whether a two-pane layout is worth drawing at all: false for a document
     * whose root has nothing to drill into, where the second pane would cost half
     * the width and show nothing.
     */
    public var twoPane: Bool
    public var dirty: Bool
    public var status: String
    public var rootKind: String
    public var hiddenCount: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The page currently being listed, with the cursor on it.
         */page: PageView, 
        /**
         * The page one level out — what a two-pane layout draws on the left, with
         * the row you came out of marked. `None` at the root, which has no parent.
         */parent: PageView?, 
        /**
         * The page the selection *would* open, so a two-pane layout at the root has
         * something to put on the right before anything has been opened. `None` when
         * the selection is not a drill row.
         */peek: PageView?, 
        /**
         * Whether a two-pane layout is worth drawing at all: false for a document
         * whose root has nothing to drill into, where the second pane would cost half
         * the width and show nothing.
         */twoPane: Bool, dirty: Bool, status: String, rootKind: String, hiddenCount: UInt32) {
        self.page = page
        self.parent = parent
        self.peek = peek
        self.twoPane = twoPane
        self.dirty = dirty
        self.status = status
        self.rootKind = rootKind
        self.hiddenCount = hiddenCount
    }
}



extension PagesView: Equatable, Hashable {
    public static func ==(lhs: PagesView, rhs: PagesView) -> Bool {
        if lhs.page != rhs.page {
            return false
        }
        if lhs.parent != rhs.parent {
            return false
        }
        if lhs.peek != rhs.peek {
            return false
        }
        if lhs.twoPane != rhs.twoPane {
            return false
        }
        if lhs.dirty != rhs.dirty {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        if lhs.rootKind != rhs.rootKind {
            return false
        }
        if lhs.hiddenCount != rhs.hiddenCount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(page)
        hasher.combine(parent)
        hasher.combine(peek)
        hasher.combine(twoPane)
        hasher.combine(dirty)
        hasher.combine(status)
        hasher.combine(rootKind)
        hasher.combine(hiddenCount)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePagesView: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PagesView {
        return
            try PagesView(
                page: FfiConverterTypePageView.read(from: &buf), 
                parent: FfiConverterOptionTypePageView.read(from: &buf), 
                peek: FfiConverterOptionTypePageView.read(from: &buf), 
                twoPane: FfiConverterBool.read(from: &buf), 
                dirty: FfiConverterBool.read(from: &buf), 
                status: FfiConverterString.read(from: &buf), 
                rootKind: FfiConverterString.read(from: &buf), 
                hiddenCount: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: PagesView, into buf: inout [UInt8]) {
        FfiConverterTypePageView.write(value.page, into: &buf)
        FfiConverterOptionTypePageView.write(value.parent, into: &buf)
        FfiConverterOptionTypePageView.write(value.peek, into: &buf)
        FfiConverterBool.write(value.twoPane, into: &buf)
        FfiConverterBool.write(value.dirty, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
        FfiConverterString.write(value.rootKind, into: &buf)
        FfiConverterUInt32.write(value.hiddenCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePagesView_lift(_ buf: RustBuffer) throws -> PagesView {
    return try FfiConverterTypePagesView.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePagesView_lower(_ value: PagesView) -> RustBuffer {
    return FfiConverterTypePagesView.lower(value)
}


/**
 * One visible line of the config tree — a projection of `flower_core::Row` for
 * the renderer. The SwiftUI side indents by `depth`, draws a disclosure twisty
 * when `is_container`, and shows `preview` as the value (or child count).
 */
public struct RowView {
    /**
     * A stable identity for this row — its dotted fig path (`server.limits.port`,
     * `tags.0`), or `""` for a scalar document. Unique among visible rows, so a
     * SwiftUI `ForEach`/`List` can key on it.
     */
    public var id: String
    /**
     * Nesting depth; top-level entries are depth 0.
     */
    public var depth: UInt32
    /**
     * The mapping key, or `[i]` for a sequence item.
     */
    public var label: String
    /**
     * The value kind as a renderer class id: `null`, `bool`, `int`, `float`,
     * `str`, `ext`, `map`, `seq`. Drives the value colour and which edit widget
     * a scalar row offers.
     */
    public var kind: String
    /**
     * A one-line rendering of the value (the scalar text, or `{n}` / `[n]` for a
     * container). For a scalar this is also the seed text an inline editor opens
     * with.
     */
    public var preview: String
    /**
     * A map or sequence (draws a twisty, toggles on tap); the complement is a
     * scalar (edited in place).
     */
    public var isContainer: Bool
    /**
     * Meaningful only for containers: whether it is currently expanded.
     */
    public var expanded: Bool
    /**
     * Whether this row is a mapping entry (its key can be renamed). `false` for a
     * sequence item, which has an index, not a key.
     */
    public var canRename: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * A stable identity for this row — its dotted fig path (`server.limits.port`,
         * `tags.0`), or `""` for a scalar document. Unique among visible rows, so a
         * SwiftUI `ForEach`/`List` can key on it.
         */id: String, 
        /**
         * Nesting depth; top-level entries are depth 0.
         */depth: UInt32, 
        /**
         * The mapping key, or `[i]` for a sequence item.
         */label: String, 
        /**
         * The value kind as a renderer class id: `null`, `bool`, `int`, `float`,
         * `str`, `ext`, `map`, `seq`. Drives the value colour and which edit widget
         * a scalar row offers.
         */kind: String, 
        /**
         * A one-line rendering of the value (the scalar text, or `{n}` / `[n]` for a
         * container). For a scalar this is also the seed text an inline editor opens
         * with.
         */preview: String, 
        /**
         * A map or sequence (draws a twisty, toggles on tap); the complement is a
         * scalar (edited in place).
         */isContainer: Bool, 
        /**
         * Meaningful only for containers: whether it is currently expanded.
         */expanded: Bool, 
        /**
         * Whether this row is a mapping entry (its key can be renamed). `false` for a
         * sequence item, which has an index, not a key.
         */canRename: Bool) {
        self.id = id
        self.depth = depth
        self.label = label
        self.kind = kind
        self.preview = preview
        self.isContainer = isContainer
        self.expanded = expanded
        self.canRename = canRename
    }
}



extension RowView: Equatable, Hashable {
    public static func ==(lhs: RowView, rhs: RowView) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.depth != rhs.depth {
            return false
        }
        if lhs.label != rhs.label {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.preview != rhs.preview {
            return false
        }
        if lhs.isContainer != rhs.isContainer {
            return false
        }
        if lhs.expanded != rhs.expanded {
            return false
        }
        if lhs.canRename != rhs.canRename {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(depth)
        hasher.combine(label)
        hasher.combine(kind)
        hasher.combine(preview)
        hasher.combine(isContainer)
        hasher.combine(expanded)
        hasher.combine(canRename)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRowView: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RowView {
        return
            try RowView(
                id: FfiConverterString.read(from: &buf), 
                depth: FfiConverterUInt32.read(from: &buf), 
                label: FfiConverterString.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf), 
                preview: FfiConverterString.read(from: &buf), 
                isContainer: FfiConverterBool.read(from: &buf), 
                expanded: FfiConverterBool.read(from: &buf), 
                canRename: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: RowView, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterUInt32.write(value.depth, into: &buf)
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterString.write(value.preview, into: &buf)
        FfiConverterBool.write(value.isContainer, into: &buf)
        FfiConverterBool.write(value.expanded, into: &buf)
        FfiConverterBool.write(value.canRename, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRowView_lift(_ buf: RustBuffer) throws -> RowView {
    return try FfiConverterTypeRowView.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRowView_lower(_ value: RowView) -> RustBuffer {
    return FfiConverterTypeRowView.lower(value)
}


/**
 * A failure constructing a document — the only fallible entry point. Every other
 * method operates on an already-parsed model and returns a [`DocView`] directly.
 */
public enum FlowerError {

    
    
    /**
     * The `format` string handed to [`FlowerDoc::new`] wasn't one flower knows.
     */
    case UnknownFormat(name: String
    )
    /**
     * fig failed to parse `source` as the requested format.
     */
    case Open(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFlowerError: FfiConverterRustBuffer {
    typealias SwiftType = FlowerError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FlowerError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .UnknownFormat(
            name: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Open(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FlowerError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .UnknownFormat(name):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(name, into: &buf)
            
        
        case let .Open(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension FlowerError: Equatable, Hashable {}

extension FlowerError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypePageView: FfiConverterRustBuffer {
    typealias SwiftType = PageView?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypePageView.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypePageView.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCrumbView: FfiConverterRustBuffer {
    typealias SwiftType = [CrumbView]

    public static func write(_ value: [CrumbView], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCrumbView.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CrumbView] {
        let len: Int32 = try readInt(&buf)
        var seq = [CrumbView]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCrumbView.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePageItemView: FfiConverterRustBuffer {
    typealias SwiftType = [PageItemView]

    public static func write(_ value: [PageItemView], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePageItemView.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PageItemView] {
        let len: Int32 = try readInt(&buf)
        var seq = [PageItemView]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePageItemView.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeRowView: FfiConverterRustBuffer {
    typealias SwiftType = [RowView]

    public static func write(_ value: [RowView], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRowView.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [RowView] {
        let len: Int32 = try readInt(&buf)
        var seq = [RowView]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRowView.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_flower_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_append_item() != 14468) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_append_root_item() != 52962) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_collapse_or_leave() != 2973) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_delete() != 14167) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_expand_or_enter() != 33225) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_insert_key() != 12563) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_insert_root_key() != 22259) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_mark_saved() != 4396) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_move_down() != 34324) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_move_row_down() != 49490) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_move_row_up() != 53382) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_move_up() != 26568) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_page_add_child() != 63713) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_page_at() != 26168) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_page_back() != 62597) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_page_delete() != 53944) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_page_move_down() != 45594) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_page_move_item_down() != 33295) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_page_move_item_up() != 29315) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_page_move_up() != 905) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_page_open() != 55615) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_page_rename() != 26084) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_page_select() != 61872) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_page_set_value() != 1068) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_pages() != 41318) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_rename_key() != 26782) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_select() != 42705) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_set_inline_budget() != 16840) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_set_value() != 43208) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_show_pages() != 54499) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_show_tree() != 7204) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_source() != 21638) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_toggle() != 62183) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_method_flowerdoc_view() != 25871) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flower_ffi_checksum_constructor_flowerdoc_new() != 32982) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all